### PR TITLE
Implement edit user profile request / response.

### PR DESCRIPTION
**Pull request by saniaky**
Related issues:
* #306 
* #242
* #106

### CODE REVIEW

**Comment by techlinesolutions** [comment]
Hi @saniaky,  how soon can this functionality be made available . I am in urgent need of this

**Comment by saniaky** [comment]
Hi @techlinesolutions. As you can see, I already made a pull request with this feature. Now we need to wait for the @brunocvcunha to approve/disapprove it or you can use my branch if you need this feature right away.

**Comment by techlinesolutions** [comment]
Thanks for your prompt response @saniaky <https://github.com/saniaky>,

Kindly share the link to your branch

I kinda need it  right away

Thanks again

**Comment by brunocvcunha** [comment]
Awesome, thank you!

**Comment by enesakin** [comment]
Hello there
I can't update the profile photo. Can you help me? I would appreciate it if you explain with examples.

**Pull request merged**
