### PR TITLE
Added story request

### PR DESCRIPTION
**Pull request by ozankaraali**

### CODE REVIEW

**Comment by ozankaraali** [comment]
I added new Instagram constants that I am not sure about its necessity; however I think that stories in an old emulation may cause ban on accounts, so I added new constants. Feel free to change.

**Comment by brunocvcunha** [comment]
Merged. Thanks a lot for the help @ozankaraali

**Comment by ozankaraali** [comment]
You're welcome @brunocvcunha

**Comment by Daedra223** [comment]
Does this commit make it possible to publish a picture as story? @ozankaraali @brunocvcunha

**Comment by ozankaraali** [comment]
Unfortunately I did not implement upload method, just gets info about stories and shows mediaId's.

**Comment by krismorte** [comment]
With this Merged I can watch my Stories only or from anybody else?

**Pull request merged**
