### PR TITLE
Core updates to Instagram4j

### LINKED ISSUE #393: "400, Something went wrong" while posting photo
Hi,

I'm uploading a photo 

```
instagram.sendRequest(new InstagramUploadVideoRequest(post.getFile(), post.getDescription()));
```
I'm 100% sure that post.getFile() return a valid FIle and post.getDescription() return a non null String
and I'm getting this ugly error

```
2019-11-19 21:40:32 [scheduling-1] INFO  org.brunocvcunha.instagram4j.Instagram4j  - Sending request: org.brunocvcunha.instagram4j.requests.InstagramUploadPhotoRequest
2019-11-19 21:40:32 [scheduling-1] INFO  org.brunocvcunha.instagram4j.requests.InstagramUploadPhotoRequest  - URL Upload: https://i.instagram.com/api/v1/upload/photo/
2019-11-19 21:40:33 [scheduling-1] INFO  org.brunocvcunha.instagram4j.requests.InstagramUploadPhotoRequest  - Photo Upload result: 400, Something is wrong. Please check your input and try again.
2019-11-19 21:40:33 [scheduling-1] INFO  org.brunocvcunha.instagram4j.requests.InstagramRequest  - Reading InstagramConfigurePhotoResult from Something is wrong. Please check your input and try again.
2019-11-19 21:40:33.521 ERROR 4696 --- [   scheduling-1] a.tassinari.core.InstaService            : Unrecognized token 'Something': was expecting ('true', 'false' or 'null')
 at [Source: (String)"Something is wrong. Please check your input and try again."; line: 1, column: 10]

com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Something': was expecting ('true', 'false' or 'null')
 at [Source: (String)"Something is wrong. Please check your input and try again."; line: 1, column: 10]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804) ~[jackson-core-2.9.9.jar:2.9.9]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:703) ~[jackson-core-2.9.9.jar:2.9.9]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2853) ~[jackson-core-2.9.9.jar:2.9.9]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1899) ~[jackson-core-2.9.9.jar:2.9.9]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:757) ~[jackson-core-2.9.9.jar:2.9.9]
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4141) ~[jackson-databind-2.9.9.jar:2.9.9]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4000) ~[jackson-databind-2.9.9.jar:2.9.9]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004) ~[jackson-databind-2.9.9.jar:2.9.9]
	at org.brunocvcunha.instagram4j.requests.InstagramRequest.parseJson(InstagramRequest.java:141) ~[instagram4j-1.11.jar:na]
	at org.brunocvcunha.instagram4j.requests.InstagramRequest.parseJson(InstagramRequest.java:111) ~[instagram4j-1.11.jar:na]
	at org.brunocvcunha.instagram4j.requests.InstagramUploadPhotoRequest.parseResult(InstagramUploadPhotoRequest.java:171) ~[instagram4j-1.11.jar:na]
	at org.brunocvcunha.instagram4j.requests.InstagramUploadPhotoRequest.execute(InstagramUploadPhotoRequest.java:106) ~[instagram4j-1.11.jar:na]
	at org.brunocvcunha.instagram4j.requests.InstagramUploadPhotoRequest.execute(InstagramUploadPhotoRequest.java:44) ~[instagram4j-1.11.jar:na]
	at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:281) ~[instagram4j-1.11.jar:na]
	at a.tassinari.core.InstaService.postPhoto(InstaService.java:67) [classes/:na]
	at a.tassinari.core.InstaService.postFile(InstaService.java:44) [classes/:na]
	at a.tassinari.core.Scheduler.schedule(Scheduler.java:41) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) [spring-context-5.2.0.M3.jar:5.2.0.M3]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.0.M3.jar:5.2.0.M3]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.0.M3.jar:5.2.0.M3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
```

I tryed different versions (1.11, 1.12, 1.13) with no results

Can you help me?

### PR DESCRIPTION
**Pull request by jvogit**
This PR updates some core features of Instagram4j.

**Updated:**

- Photo Upload to use Resumable Photo upload endpoint
- Video Upload to use Resumable Video upload endpoint
- Album Upload to upload both photo and video
- Instagram constants
- Timeline request (with pagination)

**Some notable remarks:**

- Default Headers are now applied to all request (by InstagramRequest.applyHeaders())
- Pre and Post login are requests are now in separate methods (can be called before and after login request)

Closes #393 #354

### CODE REVIEW

**Comment by Aulig** [comment]
Thank you so much for your work! Really appreciate it. So far everything is looking good to me, will let you know if i notice anything while testing.

**Comment by Raul-gupta** [comment]
@jvogit Great job!!.
But there is an issue in video upload, caption send with API is not coming.
You need to fix a small typo in code.
In class InstagramConfigureVideoRequest
change 
if (caption != null && caption.isEmpty()) {
			likeMap.put("caption", caption);
		}
To
if (caption != null && !caption.isEmpty()) {
			likeMap.put("caption", caption);
		}

**Comment by TLHP** [comment]
Worked well with this PR!
Thanks a lot jvogit

**Comment by Aulig** [comment]
Would be awesome if you could review and merge this @brunocvcunha 😃 
Just wanted to remind you in case you missed it because I know you're very busy! 
Much appreciated!

**Comment by brunocvcunha** [comment]
Thanks @jvogit

**Pull request merged**
