### PR TITLE
Add StoryQuestion and StoryCountdown metadata

### PR DESCRIPTION
**Pull request by jvogit**
Add StoryQuestion and StoryCountdown

**StoryQuestion:**
```Java
StoryQuestion story_question = StoryQuestion.builder()
        	.question("Does it work?")
        	.profile_pic_url(user.getProfile_pic_url()) //Need profile pic of current account
        	.build();
```
Note: StoryQuestion requires the profile url link to the account you are sending the story question from! This can be achieved from the InstagramLoggedUser from the InstagramLoginResult after logging in.

```Java
InstagramLoginResult result = insta.login();
InstagramLoggedUser user = result.getLogged_in_user();
user.getProfile_pic_url();
````

**StoryCountdown:**
```Java
StoryCountdown story_countdown = StoryCountdown.builder()
        	.text("Until it works!")
        	.end_ts((System.currentTimeMillis() + 1000*60*60)/1000) //UNIX Epoch of end in seconds! This adds 1 hour!
        	.build();
```
Note: The end_ts is in **seconds!**

### CODE REVIEW

**Comment by coolnickname** [comment]
I can't seem to change the digit_card_color for the story countdown. It's always blue or transparant.

Also the default value for this is #FFFFFFF, isn't this 1 F too many?

**Comment by jvogit** [comment]
> I can't seem to change the digit_card_color for the story countdown. It's always blue or transparant.
> 
> Also the default value for this is #FFFFFFF, isn't this 1 F too many?

It is working on my end.

Here is the code that I used:
```Java
StoryCountdown countdown = StoryCountdown.builder()
        	.text("Until it works!")
        	.end_ts((System.currentTimeMillis() + 1000*60*60)/1000)
        	.digit_card_color("#CD5C5C")
        	.build();
```

**Comment by brunocvcunha** [comment]
Thanks!

**Comment by coolnickname** [comment]
I'm not sure what the colour issue is, but it seems to be something I'm doing wrong so don't worry about it.

Great addition to the project, thanks a ton.

**Pull request merged**
