### PR TITLE
Add InstagramLocation and InstagramRecentActivity

### PR DESCRIPTION
**Pull request by krismorte**
/*InstagramLocation*/

I tried to put the Location in the Upload method but I get stuck
```
Instagram4j instagram = Instagram4j.builder().username("USER").password("PASS").build();			
			instagram.setup();
			instagram.login();
			
			InstagramVenueResult result=instagram.sendRequest(new InstagramGetLocationRequest("40.7439862","-73.998511"));

			System.out.println("Total: "+result.getVenues().size());
```

/*InstagramRecentActivity*/

```
InstagramRecentActivityResult result = instagram.sendRequest(new InstagramGetRecentActivityRequest());

			if (result.getAymf() != null) {
				for (InstagramItem item : result.getAymf().getItems()) {
					System.out.println(item.getUser().getUsername());
				}
			}
			System.out.println("C: " + result.getCounts().getComments());
			System.out.println("L: " + result.getCounts().getLikes());

			System.out.println("Total: " + result.getNew_stories().size());
			for (InstagramStory story : result.getNew_stories()) {
				System.out.println("S: " + story.getProfile_name());
				System.out.println("T: " + story.getArgs().get("text"));
			}

			System.out.println("Total: " + result.getOld_stories());
			for (InstagramStory story : result.getOld_stories()) {
				System.out.println("S: " + story.getProfile_name());
				System.out.println("T: " + story.getArgs().get("text"));
			}
```

### CODE REVIEW

**Comment by brunocvcunha** [comment]
Hi @krismorte 

Is it done? This PR should be merged already, or you need some help testing?

**Comment by krismorte** [comment]
This PR just maps 2 new objects and their request. I tried to get the Location and attach to the upload but without success, so the new Object can help others to do that.

**Comment by ryumaev** [comment]
look my PR #192

**Comment by ryumaev** [comment]
Yes, InstagramSearchLocationsRequest class now has geo position query parameters

**Pull request closed without merging**
