### PR TITLE
Add requests for challenge

### PR DESCRIPTION
**Pull request by cyrus07424**
Add requests for challenge

Usage:
```java
Instagram4j instagram4j = Instagram4j.builder()
        .username(USERNAME)
        .password(PASSWORD)
        .build();
instagram4j.setup();

InstagramLoginResult instagramLoginResult = instagram4j.login();

if (Objects.equals(instagramLoginResult.getStatus(), "ok")) {
    System.out.println("login success");
} else {
    if (Objects.equals(instagramLoginResult.getError_type(), "checkpoint_challenge_required")) {
        // Challenge required

        // Get challenge URL
        String challengeUrl = instagramLoginResult.getChallenge().getApi_path().substring(1);

        // Reset challenge
        String resetChallengeUrl = challengeUrl.replace("challenge", "challenge/reset");
        InstagramGetChallengeResult getChallengeResult = instagram4j
                .sendRequest(new InstagramResetChallengeRequest(resetChallengeUrl));

        // If action is close
        if (Objects.equals(getChallengeResult.getAction(), "close")) {
            // Get challenge
            getChallengeResult = instagram4j
                    .sendRequest(new InstagramGetChallengeRequest(challengeUrl));
        }

        if (Objects.equals(getChallengeResult.getStep_name(), "select_verify_method")) {

            // Get security code
            InstagramSelectVerifyMethodResult postChallengeResult = instagram4j
                    .sendRequest(new InstagramSelectVerifyMethodRequest(challengeUrl,
                            getChallengeResult.getStep_data().getChoice()));

            System.out.println("input security code");
            String securityCode = null;
            try (Scanner scanner = new Scanner(System.in)) {
                securityCode = scanner.nextLine();
            }

            // Send security code
            InstagramLoginResult securityCodeInstagramLoginResult = instagram4j
                    .sendRequest(new InstagramSendSecurityCodeRequest(challengeUrl, securityCode));

            if (Objects.equals(securityCodeInstagramLoginResult.getStatus(), "ok")) {
                System.out.println("login success");
            } else {
                System.out.println("login failed");
            }
        }
    }
}
```

### CODE REVIEW

**Comment by LearnJava** [comment]
Hello! Where is InstagramResetChallengeRequest ? I can not find it.

**Comment by cyrus07424** [comment]
@LearnJava 
Sorry. I forgotten it.

**Comment by jemand771** [comment]
If this works, you are my hero. I'll test once I get my bot account banned the next time

**Comment by newsbubbles** [comment]
Worked 100% I totally recommend adding the pull to base ;)

**Comment by AuligPromotions** [comment]
Can this get merged please? Would be great 👍

**Comment by heroys6** [comment]
Please accept this pull request!

**Comment by brunocvcunha** [comment]
Sweet, thanks!

**Comment by generalbytes** [comment]
Thank you @brunocvcunha

**Comment by DeBerk** [comment]
What if the "step_name" is qual to "submit_phone"? 

In that case the InstagramSendSecurityCodeRequest fails.

org.brunocvcunha.instagram4j.Instagram4j  - Sending request: org.brunocvcunha.instagram4j.requests.InstagramSendSecurityCodeRequest
org.brunocvcunha.instagram4j.requests.InstagramRequest  - Reading InstagramLoginResult from {"message": "This field is required.", "status": "fail"}

**Comment by cyrus07424** [comment]
@DeBerk 

Here is the full Login code.

```java
import java.util.Objects;
import java.util.Scanner;
import org.brunocvcunha.instagram4j.Instagram4j;
import org.brunocvcunha.instagram4j.requests.InstagramGetChallengeRequest;
import org.brunocvcunha.instagram4j.requests.InstagramResetChallengeRequest;
import org.brunocvcunha.instagram4j.requests.InstagramSelectVerifyMethodRequest;
import org.brunocvcunha.instagram4j.requests.InstagramSendSecurityCodeRequest;
import org.brunocvcunha.instagram4j.requests.payload.InstagramGetChallengeResult;
import org.brunocvcunha.instagram4j.requests.payload.InstagramLoginResult;
import org.brunocvcunha.instagram4j.requests.payload.InstagramSelectVerifyMethodResult;

/**
 * Instagram Login Example.
 *
 * @author cyrus
 */
public class InstagramLoginExample {

	/**
	 * main.
	 *
	 * @param args
	 * @throws Exception
	 */
	public static void main(String[] args) throws Exception {
		// Setup
		Instagram4j instagram4j = Instagram4j.builder()
				.username(USERNAME)
				.password(PASSWORD)
				.build();
		instagram4j.setup();

		// Get login response
		InstagramLoginResult instagramLoginResult = instagram4j.login();

		// Check login response
		checkInstagramLoginResult(instagram4j, instagramLoginResult, true);
	}

	/**
	 * Check login response.
	 *
	 * @param instagram4j
	 * @param instagramLoginResult
	 * @param doReAuthentication
	 * @throws Exception
	 */
	public static void checkInstagramLoginResult(Instagram4j instagram4j, InstagramLoginResult instagramLoginResult,
			boolean doReAuthentication) throws Exception {
		if (Objects.equals(instagramLoginResult.getStatus(), "ok")
				&& instagramLoginResult.getLogged_in_user() != null) {
			// Login success
			System.out.println("■Login success.");
			System.out.println(instagramLoginResult.getLogged_in_user());
		} else if (Objects.equals(instagramLoginResult.getStatus(), "ok")) {
			// Logged in user not exists
			System.out.println("■Logged in user not exists.");

			// TODO
		} else if (Objects.equals(instagramLoginResult.getStatus(), "fail")) {
			// Login failed

			// Check error type
			if (Objects.equals(instagramLoginResult.getError_type(), "checkpoint_challenge_required")) {
				System.out.println("■Challenge URL : " + instagramLoginResult.getChallenge().getUrl());

				// If do re-authentication
				if (doReAuthentication) {
					// Get challenge URL
					String challengeUrl = instagramLoginResult.getChallenge().getApi_path().substring(1);

					// Reset
					String resetUrl = challengeUrl.replace("challenge", "challenge/reset");
					InstagramGetChallengeResult getChallengeResult = instagram4j
							.sendRequest(new InstagramResetChallengeRequest(resetUrl));
					System.out.println("■Reset result : " + getChallengeResult);

					// if "close"
					if (Objects.equals(getChallengeResult.getAction(), "close")) {
						// Get challenge response
						getChallengeResult = instagram4j
								.sendRequest(new InstagramGetChallengeRequest(challengeUrl));
						System.out.println("■Challenge response : " + getChallengeResult);
					}

					// Check step name
					if (Objects.equals(getChallengeResult.getStep_name(), "select_verify_method")) {
						// Select verify method

						// Get select verify method result
						InstagramSelectVerifyMethodResult postChallengeResult = instagram4j
								.sendRequest(new InstagramSelectVerifyMethodRequest(challengeUrl,
										getChallengeResult.getStep_data().getChoice()));

						// If "close"
						if (Objects.equals(postChallengeResult.getAction(), "close")) {
							// Challenge was closed
							System.out.println("■Challenge was closed : " + postChallengeResult);

							// End
							return;
						}

						// Security code has been sent
						System.out.println("■Security code has been sent : " + postChallengeResult);

						// Please input Security code
						System.out.println("Please input Security code");
						String securityCode = null;
						try (Scanner scanner = new Scanner(System.in)) {
							securityCode = scanner.nextLine();
						}

						// Send security code
						InstagramLoginResult securityCodeInstagramLoginResult = instagram4j
								.sendRequest(new InstagramSendSecurityCodeRequest(challengeUrl, securityCode));

						// Check login response
						checkInstagramLoginResult(instagram4j, securityCodeInstagramLoginResult, false);
					} else if (Objects.equals(getChallengeResult.getStep_name(), "verify_email")) {
						// Security code has been sent to E-mail
						System.out.println("■Security code has been sent to E-mail");

						// TODO
					} else if (Objects.equals(getChallengeResult.getStep_name(), "verify_code")) {
						// Security code has been sent to phone
						System.out.println("■Security code has been sent to phone");

						// TODO
					} else if (Objects.equals(getChallengeResult.getStep_name(), "submit_phone")) {
						// Unknown
						System.out.println("■Unknown.");

						// TODO
					} else if (Objects.equals(getChallengeResult.getStep_name(), "delta_login_review")) {
						// Maybe showing security confirmation view?
						System.out.println("■Maybe showing security confirmation view?");

						// FIXME Send request with choice
						InstagramSelectVerifyMethodResult instagramSelectVerifyMethodResult = instagram4j
								.sendRequest(new InstagramSelectVerifyMethodRequest(challengeUrl,
										getChallengeResult.getStep_data().getChoice()));
						System.out.println(instagramSelectVerifyMethodResult);

						// TODO
					} else if (Objects.equals(getChallengeResult.getStep_name(), "change_password")) {
						// Change password needed
						System.out.println("■Change password needed.");
					} else if (Objects.equals(getChallengeResult.getAction(), "close")) {
						// Maybe already challenge closed at other device
						System.out.println("■Maybe already challenge closed at other device.");

						// TODO
					} else {
						// TODO Other
						System.out.println("■Other.");
					}
				}
			} else if (Objects.equals(instagramLoginResult.getError_type(), "bad_password")) {
				System.out.println("■Bad password.");
				System.out.println(instagramLoginResult.getMessage());
			} else if (Objects.equals(instagramLoginResult.getError_type(), "rate_limit_error")) {
				System.out.println("■Too many request.");
				System.out.println(instagramLoginResult.getMessage());
			} else if (Objects.equals(instagramLoginResult.getError_type(), "invalid_parameters")) {
				System.out.println("■Invalid parameter.");
				System.out.println(instagramLoginResult.getMessage());
			} else if (Objects.equals(instagramLoginResult.getError_type(), "needs_upgrade")) {
				System.out.println("■App upgrade needed.");
				System.out.println(instagramLoginResult.getMessage());
			} else if (Objects.equals(instagramLoginResult.getError_type(), "sentry_block")) {
				System.out.println("■Sentry block.");
				System.out.println(instagramLoginResult.getMessage());
			} else if (Objects.equals(instagramLoginResult.getError_type(), "inactive user")) {
				System.out.println("■Inactive user.");
				System.out.println(instagramLoginResult.getMessage());
			} else if (Objects.equals(instagramLoginResult.getError_type(), "unusable_password")) {
				System.out.println("■Unusable password.");
				System.out.println(instagramLoginResult.getMessage());
			} else if (instagramLoginResult.getTwo_factor_info() != null) {
				System.out.println("■Two factor authentication needed.");
				System.out.println(instagramLoginResult.getMessage());

				// If do re-authentication
				if (doReAuthentication) {
					// Two factor authentication
					InstagramLoginResult twoFactorInstagramLoginResult = instagram4j.login(VERIFICATION_CODE);

					// Check login result
					checkInstagramLoginResult(instagram4j, twoFactorInstagramLoginResult, false);
				}
			} else if (Objects.equals(instagramLoginResult.getMessage(),
					"Please check the code we sent you and try again.")) {
				System.out.println("■Invalid security code.");
				System.out.println(instagramLoginResult.getMessage());
			} else if (Objects.equals(instagramLoginResult.getMessage(),
					"This code has expired. Go back to request a new one.")) {
				System.out.println("■Security code has expired.");
				System.out.println(instagramLoginResult.getMessage());
			} else if (instagramLoginResult.getChallenge() != null) {
				System.out.println("■Challenge : " + instagramLoginResult.getChallenge());
				System.out.println(instagramLoginResult.getMessage());
				if (instagramLoginResult.getChallenge().getLock() != null
						&& instagramLoginResult.getChallenge().getLock()) {
					// Login locked
					System.out.println("■Login locked.");
				} else {
					// Logged in user exists, or maybe showing security code
					// view on other device
					System.out.println("■Logged in user exists, or maybe showing security code view on other device.");
				}
			} else {
				System.out.println("■Unknown error : " + instagramLoginResult.getError_type());
				System.out.println(instagramLoginResult.getMessage());
			}
		} else {
			System.out.println("■Unknon status : " + instagramLoginResult.getStatus());
			System.out.println(instagramLoginResult.getMessage());
		}
	}
}
```

**Comment by heroys6** [comment]
@cyrus07424 A few weeks ago your code was working well. After that I did not use API. And now I always receive nulls in `InstagramGetChallengeResult` response and cannot pass the login. 
I'm using your code from the [previous post](https://github.com/brunocvcunha/instagram4j/pull/358#issuecomment-552099530).
Screenshot from debugger: [link](https://prnt.sc/pzt7z4)
Please help.

**Comment by heroys6** [comment]
Ok, it seems like I have been banned. Every time I tried to login(Android device/Web) I see "Help Us Confirm You Own This Account". Reset password via phone number didn't help. So. If your `InstagramGetChallengeResult` is full of nulls - check isn't your account is banned ;)

**Comment by vadimTovstik** [comment]
> Ok, it seems like I have been banned. Every time I tried to login(Android device/Web) I see "Help Us Confirm You Own This Account". Reset password via phone number didn't help. So. If your `InstagramGetChallengeResult` is full of nulls - check isn't your account is banned ;)

Do you have a message "Wait a few minute" in the InstagramGetChallengeResult object?

**Comment by heroys6** [comment]
> Do you have a message "Wait a few minute" in the InstagramGetChallengeResult object?
No

**Comment by vadimTovstik** [comment]
> > Do you have a message "Wait a few minute" in the InstagramGetChallengeResult object?
> 
> No. I have provided a screenshot a few posts above.

maybe you have a similar problem like mine. so your account is still banned or not.

**Comment by lk529389** [comment]
Thank you very much for solving my problem, I love you

**Comment by OmidPvh** [comment]
Hi... Is so important to me that solve Login Problem but
This Code Does not work to me 
When i try send InstagramGetChallengeRequest 
I have This Error -> JsonParseException :

com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
at [Source: (String)"<!DOCTYPE html>
<html lang="en" class="no-js not-logged-in ">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>
Page Not Found &bull; Instagram
</title>
<meta name="robots" content="noimageindex, noarchive">
<meta name="apple-mobile-web-app-status-bar-style" content="default">
<meta name="mobile-web-app-capable" content="yes">
<meta name="theme-color""[truncated 20213 chars]; line: 1, column: 2]
at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:693)
at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:591)
at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1902)
at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:757)
at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4142)
at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3005)
at org.brunocvcunha.instagram4j.requests.InstagramRequest.parseJson(InstagramRequest.java:126)
at org.brunocvcunha.instagram4j.InstagramRequest.parseJson(InstagramRequest.java:96)
at org.brunocvcunha.instagram4j.requests.InstagramResetChallengeRequest.parseResult(InstagramResetChallengeRequest.java:58)
at org.brunocvcunha.instagram4j.requests.InstagramResetChallengeRequest.parseResult(InstagramResetChallengeRequest.java:34)
at org.brunocvcunha.instagram4j.requests.InstagramPostRequest.execute(InstagramPostRequest.java:79)
at org.brunocvcunha.instagram4j..Instagram4j.sendRequest(Instagram4j.java:423)
at com.a.practice2.MainActivity$1.doInBackground(MainActivity.java:111)
at com.a.practice2.MainActivity$1.doInBackground(MainActivity.java:48)
at android.os.AsyncTask$2.call(AsyncTask.java:292)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)

Anyone Help?

**Comment by OmidPvh** [comment]
> @DeBerk
> 
> Here is the full Login code.
> 
> ```java
> import java.util.Objects;
> import java.util.Scanner;
> import org.brunocvcunha.instagram4j.Instagram4j;
> import org.brunocvcunha.instagram4j.requests.InstagramGetChallengeRequest;
> import org.brunocvcunha.instagram4j.requests.InstagramResetChallengeRequest;
> import org.brunocvcunha.instagram4j.requests.InstagramSelectVerifyMethodRequest;
> import org.brunocvcunha.instagram4j.requests.InstagramSendSecurityCodeRequest;
> import org.brunocvcunha.instagram4j.requests.payload.InstagramGetChallengeResult;
> import org.brunocvcunha.instagram4j.requests.payload.InstagramLoginResult;
> import org.brunocvcunha.instagram4j.requests.payload.InstagramSelectVerifyMethodResult;
> 
> /**
>  * Instagram Login Example.
>  *
>  * @author cyrus
>  */
> public class InstagramLoginExample {
> 
> 	/**
> 	 * main.
> 	 *
> 	 * @param args
> 	 * @throws Exception
> 	 */
> 	public static void main(String[] args) throws Exception {
> 		// Setup
> 		Instagram4j instagram4j = Instagram4j.builder()
> 				.username(USERNAME)
> 				.password(PASSWORD)
> 				.build();
> 		instagram4j.setup();
> 
> 		// Get login response
> 		InstagramLoginResult instagramLoginResult = instagram4j.login();
> 
> 		// Check login response
> 		checkInstagramLoginResult(instagram4j, instagramLoginResult, true);
> 	}
> 
> 	/**
> 	 * Check login response.
> 	 *
> 	 * @param instagram4j
> 	 * @param instagramLoginResult
> 	 * @param doReAuthentication
> 	 * @throws Exception
> 	 */
> 	public static void checkInstagramLoginResult(Instagram4j instagram4j, InstagramLoginResult instagramLoginResult,
> 			boolean doReAuthentication) throws Exception {
> 		if (Objects.equals(instagramLoginResult.getStatus(), "ok")
> 				&& instagramLoginResult.getLogged_in_user() != null) {
> 			// Login success
> 			System.out.println("■Login success.");
> 			System.out.println(instagramLoginResult.getLogged_in_user());
> 		} else if (Objects.equals(instagramLoginResult.getStatus(), "ok")) {
> 			// Logged in user not exists
> 			System.out.println("■Logged in user not exists.");
> 
> 			// TODO
> 		} else if (Objects.equals(instagramLoginResult.getStatus(), "fail")) {
> 			// Login failed
> 
> 			// Check error type
> 			if (Objects.equals(instagramLoginResult.getError_type(), "checkpoint_challenge_required")) {
> 				System.out.println("■Challenge URL : " + instagramLoginResult.getChallenge().getUrl());
> 
> 				// If do re-authentication
> 				if (doReAuthentication) {
> 					// Get challenge URL
> 					String challengeUrl = instagramLoginResult.getChallenge().getApi_path().substring(1);
> 
> 					// Reset
> 					String resetUrl = challengeUrl.replace("challenge", "challenge/reset");
> 					InstagramGetChallengeResult getChallengeResult = instagram4j
> 							.sendRequest(new InstagramResetChallengeRequest(resetUrl));
> 					System.out.println("■Reset result : " + getChallengeResult);
> 
> 					// if "close"
> 					if (Objects.equals(getChallengeResult.getAction(), "close")) {
> 						// Get challenge response
> 						getChallengeResult = instagram4j
> 								.sendRequest(new InstagramGetChallengeRequest(challengeUrl));
> 						System.out.println("■Challenge response : " + getChallengeResult);
> 					}
> 
> 					// Check step name
> 					if (Objects.equals(getChallengeResult.getStep_name(), "select_verify_method")) {
> 						// Select verify method
> 
> 						// Get select verify method result
> 						InstagramSelectVerifyMethodResult postChallengeResult = instagram4j
> 								.sendRequest(new InstagramSelectVerifyMethodRequest(challengeUrl,
> 										getChallengeResult.getStep_data().getChoice()));
> 
> 						// If "close"
> 						if (Objects.equals(postChallengeResult.getAction(), "close")) {
> 							// Challenge was closed
> 							System.out.println("■Challenge was closed : " + postChallengeResult);
> 
> 							// End
> 							return;
> 						}
> 
> 						// Security code has been sent
> 						System.out.println("■Security code has been sent : " + postChallengeResult);
> 
> 						// Please input Security code
> 						System.out.println("Please input Security code");
> 						String securityCode = null;
> 						try (Scanner scanner = new Scanner(System.in)) {
> 							securityCode = scanner.nextLine();
> 						}
> 
> 						// Send security code
> 						InstagramLoginResult securityCodeInstagramLoginResult = instagram4j
> 								.sendRequest(new InstagramSendSecurityCodeRequest(challengeUrl, securityCode));
> 
> 						// Check login response
> 						checkInstagramLoginResult(instagram4j, securityCodeInstagramLoginResult, false);
> 					} else if (Objects.equals(getChallengeResult.getStep_name(), "verify_email")) {
> 						// Security code has been sent to E-mail
> 						System.out.println("■Security code has been sent to E-mail");
> 
> 						// TODO
> 					} else if (Objects.equals(getChallengeResult.getStep_name(), "verify_code")) {
> 						// Security code has been sent to phone
> 						System.out.println("■Security code has been sent to phone");
> 
> 						// TODO
> 					} else if (Objects.equals(getChallengeResult.getStep_name(), "submit_phone")) {
> 						// Unknown
> 						System.out.println("■Unknown.");
> 
> 						// TODO
> 					} else if (Objects.equals(getChallengeResult.getStep_name(), "delta_login_review")) {
> 						// Maybe showing security confirmation view?
> 						System.out.println("■Maybe showing security confirmation view?");
> 
> 						// FIXME Send request with choice
> 						InstagramSelectVerifyMethodResult instagramSelectVerifyMethodResult = instagram4j
> 								.sendRequest(new InstagramSelectVerifyMethodRequest(challengeUrl,
> 										getChallengeResult.getStep_data().getChoice()));
> 						System.out.println(instagramSelectVerifyMethodResult);
> 
> 						// TODO
> 					} else if (Objects.equals(getChallengeResult.getStep_name(), "change_password")) {
> 						// Change password needed
> 						System.out.println("■Change password needed.");
> 					} else if (Objects.equals(getChallengeResult.getAction(), "close")) {
> 						// Maybe already challenge closed at other device
> 						System.out.println("■Maybe already challenge closed at other device.");
> 
> 						// TODO
> 					} else {
> 						// TODO Other
> 						System.out.println("■Other.");
> 					}
> 				}
> 			} else if (Objects.equals(instagramLoginResult.getError_type(), "bad_password")) {
> 				System.out.println("■Bad password.");
> 				System.out.println(instagramLoginResult.getMessage());
> 			} else if (Objects.equals(instagramLoginResult.getError_type(), "rate_limit_error")) {
> 				System.out.println("■Too many request.");
> 				System.out.println(instagramLoginResult.getMessage());
> 			} else if (Objects.equals(instagramLoginResult.getError_type(), "invalid_parameters")) {
> 				System.out.println("■Invalid parameter.");
> 				System.out.println(instagramLoginResult.getMessage());
> 			} else if (Objects.equals(instagramLoginResult.getError_type(), "needs_upgrade")) {
> 				System.out.println("■App upgrade needed.");
> 				System.out.println(instagramLoginResult.getMessage());
> 			} else if (Objects.equals(instagramLoginResult.getError_type(), "sentry_block")) {
> 				System.out.println("■Sentry block.");
> 				System.out.println(instagramLoginResult.getMessage());
> 			} else if (Objects.equals(instagramLoginResult.getError_type(), "inactive user")) {
> 				System.out.println("■Inactive user.");
> 				System.out.println(instagramLoginResult.getMessage());
> 			} else if (Objects.equals(instagramLoginResult.getError_type(), "unusable_password")) {
> 				System.out.println("■Unusable password.");
> 				System.out.println(instagramLoginResult.getMessage());
> 			} else if (instagramLoginResult.getTwo_factor_info() != null) {
> 				System.out.println("■Two factor authentication needed.");
> 				System.out.println(instagramLoginResult.getMessage());
> 
> 				// If do re-authentication
> 				if (doReAuthentication) {
> 					// Two factor authentication
> 					InstagramLoginResult twoFactorInstagramLoginResult = instagram4j.login(VERIFICATION_CODE);
> 
> 					// Check login result
> 					checkInstagramLoginResult(instagram4j, twoFactorInstagramLoginResult, false);
> 				}
> 			} else if (Objects.equals(instagramLoginResult.getMessage(),
> 					"Please check the code we sent you and try again.")) {
> 				System.out.println("■Invalid security code.");
> 				System.out.println(instagramLoginResult.getMessage());
> 			} else if (Objects.equals(instagramLoginResult.getMessage(),
> 					"This code has expired. Go back to request a new one.")) {
> 				System.out.println("■Security code has expired.");
> 				System.out.println(instagramLoginResult.getMessage());
> 			} else if (instagramLoginResult.getChallenge() != null) {
> 				System.out.println("■Challenge : " + instagramLoginResult.getChallenge());
> 				System.out.println(instagramLoginResult.getMessage());
> 				if (instagramLoginResult.getChallenge().getLock() != null
> 						&& instagramLoginResult.getChallenge().getLock()) {
> 					// Login locked
> 					System.out.println("■Login locked.");
> 				} else {
> 					// Logged in user exists, or maybe showing security code
> 					// view on other device
> 					System.out.println("■Logged in user exists, or maybe showing security code view on other device.");
> 				}
> 			} else {
> 				System.out.println("■Unknown error : " + instagramLoginResult.getError_type());
> 				System.out.println(instagramLoginResult.getMessage());
> 			}
> 		} else {
> 			System.out.println("■Unknown status : " + instagramLoginResult.getStatus());
> 			System.out.println(instagramLoginResult.getMessage());
> 		}
> 	}
> }
> ```

Hi... 
This Code Does not work to me
when i try get instagramLoginResult.getChallenge().getApi_path() so return null and 
when i try send InstagramGetChallengeRequest return -> JsonParseException .
What should i do to solve this problem?

**Comment by hippolyto** [comment]
> Here is the full Login code.
> 

I've got:

```
Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
	VERIFICATION_CODE cannot be resolved to a variable

```
How can I solve it? Thank you.

**Comment by mohamed-kms** [comment]
Can somebody please help me? I tried the code but still I'm getting message=login_required when I run user search request

**Comment by fakefacebook** [comment]
Hello @cyrus07424 help me here

when i am getting challenge required then i am stuck here 
```
InstagramGetChallengeResult getChallengeResult = instagram4j
							.sendRequest(new InstagramResetChallengeRequest(resetUrl));
					System.out.println("■Reset result : " + getChallengeResult);

```

this is throw error like "login first". please help me.

**Comment by mohamed-kms** [comment]
> Hello @cyrus07424 help me here
> 
> when i am getting challenge required then i am stuck here
> 
> ```
> InstagramGetChallengeResult getChallengeResult = instagram4j
> 							.sendRequest(new InstagramResetChallengeRequest(resetUrl));
> 					System.out.println("■Reset result : " + getChallengeResult);
> ```
> 
> this is throw error like "`Need to login first!`". please help me.

You need to do this part before:
// Setup
		Instagram4j instagram4j = Instagram4j.builder()
				.username(USERNAME)
				.password(PASSWORD)
				.build();
		instagram4j.setup();

		// Get login response
		InstagramLoginResult instagramLoginResult = instagram4j.login();

**Comment by fakefacebook** [comment]
> 
> 
> You need to do this part before:
> // Setup
> Instagram4j instagram4j = Instagram4j.builder()
> .username(USERNAME)
> .password(PASSWORD)
> .build();
> instagram4j.setup();
> 
> ```
> 	// Get login response
> 	InstagramLoginResult instagramLoginResult = instagram4j.login();
> ```

I did this Already. After login failed this method i called same as this code 
https://github.com/instagram4j/instagram4j/pull/358#issuecomment-599417085

**Pull request merged**
