### PR TITLE
Added ability to upload photo to Story

### PR DESCRIPTION
**Pull request by jvogit**
Added ability to upload a photo to your story or direct story and metadata.

To upload story:
To use story photo upload and apply metadata (like polls, etc.)
```Java
File img = ...
Collection<StoryMetadata> metadatas = ...

InstagramUploadStoryPhotoRequest req = new InstagramUploadStoryPhotoRequest(img, metadatas);
InstagramUploadStoryPhotoRequest req = new InstagramUploadStoryPhotoRequest(img); // w/o metadata
InstagramUploadStoryPhotoRequest req = new InstagramUploadStoryPhotoRequest(img, metadatas, "thread id"); //direct story upload

InstagramConfigureStoryResult result = api.sendRequest(req);
```
To create metadata:
For Story:
```Java
StoryPoll poll = StoryPoll.builder()
                .question("Is Java cool?") //Note: won't actually draw question to image. Only poll sticker will appear
                .tallies(Arrays.asList(Tally.YES, Tally.NO)) //Only 2 tallies per story poll
                .x(0.5) //center range 0.0 - 1.0
                .y(0.5) //center range 0.0 - 1.0
                .width(1.0) //range 0.0 - 1.0
                .height(1.0) //range 0.0 - 1.0
                .build();
```
For custom Tally:
```Java
Tally custom_tally = Tally.builder()
                .text("Custom") //Custom text
                .font_size(20) //Custom font size range 17.5 - 35.0
                .build();
```
For Hashtag:
NOTE: will only make area interactive. WILL NOT draw hashtag sticker
```Java
StoryHashtag hashtag = StoryHashtag.builder()
                .tag_name("java") //tag without '#'
                .build(); //asign x y z rotation for position of tag
```
For Mentions:
NOTE: same applies. will only make area interactive.
```Java
ReelMention rmention = ReelMention.builder()
                .user_id("user id/pk") //pk
                .build(); //assign x y z rotation for position of tag
        
        StoryMention mention = StoryMention.builder()
                .reel_mentions(Arrays.asList(rmention)) //all ReelMention
                .build();
```
You can also fetch stickers and get image links for you to apply yourself!
```Java
InstagramStickerRequest req = new InstagramStickerRequest();
        
InstagramStickerRequestResult res = insta.sendRequest(req);
        
res.getStatic_stickers()
    .forEach(stick -> {
        if(stick.getStickers() != null) {
            stick.getStickers().stream().forEach(data -> {
                System.out.println(data.getId() + " " + data.getImage_url());
            });
        }
});
```
I hope to implement more metadata to stories and implement direct stories soon.

### CODE REVIEW

**Comment by jvogit** [comment]
Leave it open for now!

**Comment by jvogit** [comment]
@brunocvcunha
You can accept it for now.

**Comment by jvogit** [comment]
@brunocvcunha
I think it'd be better to leave it open and wait for direct stories to be implemented and some features!

**Comment by krismorte** [comment]
@jvogit are you will create metadata to the image bounds too?

**Comment by jvogit** [comment]
@krismorte
What are image bounds? Im not aware on this.

**Comment by krismorte** [comment]
Sorry, it's not bound but the image position when you upload the image at IG Story you can approximate or give some distance at the picture.

**Comment by jvogit** [comment]
@krismorte 
sorry i still do not know what you mean. is it like cropping? (if so must do manually unless i could write some photo processing classes built in) could you explain better for me?

**Comment by krismorte** [comment]
It's no the cropping is more like zoom. When you upload a picture bigger then screen you can zoom in or out.

**Comment by jvogit** [comment]
@krismorte 
Oh i know. I assume it's just photo processing and must be done yourself but it could help for this api to have some tools. could come up a way to have some photo processing utils in this api such as applying stickers and such.

**Comment by jvogit** [comment]
@brunocvcunha 
its ready to be merged.

**Comment by brunocvcunha** [comment]
A lot of work guys! Thank you @jvogit and @krismorte for the collaboration.

**Comment by gss0** [comment]
Hi, 
i'm unable to view metadata about my stories. It only displays the image and an empty div with all the dimensions set (... x(0.5).y(0.5).height(0.5) ) . What am I doing wrong?

This is the code used:
```
Collection<StoryMetadata> metadatas = new ArrayList<StoryMetadata>();
StoryCountdown story_countdown = StoryCountdown.builder().text("Aste in scadenza !").end_ts(new SimpleDateFormat("dd-MM-yyyy HH:mm:ss").parse("10-09-2019 14:45:00").getTime() * 1000).x(0.5).y(0.5).height(0.5).build();
metadatas.add(story_countdown);
InstagramUploadStoryPhotoRequest req = new InstagramUploadStoryPhotoRequest(imageToUpload, metadatas);
InstagramConfigureStoryResult result = instagram.sendRequest(req);
```
thanks

**Comment by jvogit** [comment]
@gss0
Please refer to #352 and see if it solves your issue. I've updated InstagramConfigureResult to the correct models. Additionally, please refer to #359 because you need to update InstagramConstants to receive the correct story metadata when you crawl stories.

If your issue isn't solved, please open a new Issue instead of replying here.

**Pull request merged**
