### PR TITLE
[WIP] Update InstagramTimelineFeedRequest to use Post request

### PR DESCRIPTION
**Pull request by jvogit**
This PR fixes InstagramTimelineFeedRequest to use a Post request.
This also fixes issues with the InstagramComment PK that are no longer of type long.
Also update models.
#354 
#310

### CODE REVIEW

**Comment by tayfunyasar** [comment]
Will you @brunocvcunha approve this one? Because https://github.com/brunocvcunha/instagram4j/issues/354 not working.

**Comment by danilbykov** [comment]
@jvogit, did you try to load feed with non-null `maxId`? I load the most recent posts with `maxId = null`. Take `getNext_max_id` from this response (it is not null) and make second InstagramTimelineFeedRequest with this `maxId`. Second request returns the same results as first request. So non-null `maxId` doesn't affect on result.

I compared your code with corresponded code from
https://github.com/mgp25/Instagram-API/blob/master/src/Request/Timeline.php
But I don't see difference.

**Comment by jvogit** [comment]
@danilbykov, I've been looking into this issue as the pagination doesn't seem to work in the current state. From what I can discover, it is due to the outdated InstagramConstants. There is already a PR that updates the constants to match the php library. There are also additional headers needed (So far X-IG-App-ID and X-IG-Capabilities and others as well) for sending requests which I will update this PR to include them (or create another one). I will update when I'm sure the pagination works as intended. 

#359

**Comment by danilbykov** [comment]
Hmm, I updated InstagramConstants as you said from #359 and added these headers
```
payload.put("X-Ads-Opt-Out", "0");
payload.put("X-Google-AD-ID", api.getAdvertisingId());
payload.put("X-DEVICE-ID", api.getUuid());
```
but nothing is changed.

I will try again later or will wait your changes. Thanks for looking into this.

**Comment by jvogit** [comment]
@danilbykov, It's a confusing problem. I am able to get the updated timeline feed response but I can't seem to find a way to get the pagination to work.

**Comment by GetsEclectic** [comment]
I tried the same thing and it didn't help. Maybe one of the other ids needs to be set?

**Comment by jvogit** [comment]
With #411

**Comment by yaniferhaoui** [comment]
Hi, the InstagramTimelineFeedRequest doesn't work for me. The request doesn't return items...
I just passed an empty nextMaxId at the first call and then the nextMaxId returned, the problem persists...
Someone has any solutions to fix InstagramTimelineFeedRequest ?

Here my response :
`InstagramFeedResult(super=StatusResult(status=ok, message=null, spam=false, lock=false, feedback_title=null, feedback_message=null, error_type=null, checkpoint_url=null), auto_load_more_enabled=true, num_results=10, next_max_id=KFEAwKONFjTMOh-ArpZgEQ06HwDbJdFamjofffuA7JTSOh_7LIWkwSg4H7KJAW-KKxkfuSAgVHCSOh8adg7wDOomH3vMBsFzlTgfnaIrggkjOh8Wto2CuY5cAA==, items=null, ranked_items=null, more_available=true)
`

Thanks

**Comment by jvogit** [comment]
> Hi, the InstagramTimelineFeedRequest doesn't work for me. The request doesn't return items...
> I just passed an empty nextMaxId at the first call and then the nextMaxId returned, the problem persists...
> Someone has any solutions to fix InstagramTimelineFeedRequest ?
> 
> Here my response :
> `InstagramFeedResult(super=StatusResult(status=ok, message=null, spam=false, lock=false, feedback_title=null, feedback_message=null, error_type=null, checkpoint_url=null), auto_load_more_enabled=true, num_results=10, next_max_id=KFEAwKONFjTMOh-ArpZgEQ06HwDbJdFamjofffuA7JTSOh_7LIWkwSg4H7KJAW-KKxkfuSAgVHCSOh8adg7wDOomH3vMBsFzlTgfnaIrggkjOh8Wto2CuY5cAA==, items=null, ranked_items=null, more_available=true) `
> 
> Thanks

Hi, please see #411 as the InstagramTimelineFeedRequest is working in that PR.

Here's a link to it as well, [here](https://github.com/jvogit/instagram4j/blob/media-upload/src/main/java/org/brunocvcunha/instagram4j/requests/InstagramTimelineFeedRequest.java)

**Pull request closed without merging**
